/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "info.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
print_info_x_1(struct arg arg1, void *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, print_info_x,
		(xdrproc_t) xdr_arg, (caddr_t) &arg1,
		(xdrproc_t) xdr_void, (caddr_t) clnt_res,
		TIMEOUT));
}
