/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "info.h"
#include <stdio.h>


pthread_mutex_t mutex;

bool_t print_info_x_1_svc(struct arg arg1, void *result,  struct svc_req *rqstp) {


	pthread_mutex_lock(&mutex);

	printf("%s\t%s %s\t%s\n", arg1.user, arg1.op, arg1.f_name, arg1.date);

	pthread_mutex_unlock(&mutex);


	return 1;
}

int info_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result) {
	xdr_free (xdr_result, result);

	/*
	 * Insert additional freeing code here, if needed
	 */

	return 1;
}
