/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _INFO_H_RPCGEN
#define _INFO_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct arg {
	char user[256];
	char op[16];
	char date[32];
	char f_name[256];
};
typedef struct arg arg;

#define INFO 99
#define INFOVER 1

#if defined(__STDC__) || defined(__cplusplus)
#define print_info_x 1
extern  enum clnt_stat print_info_x_1(struct arg , void *, CLIENT *);
extern  bool_t print_info_x_1_svc(struct arg , void *, struct svc_req *);
extern int info_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define print_info_x 1
extern  enum clnt_stat print_info_x_1();
extern  bool_t print_info_x_1_svc();
extern int info_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_arg (XDR *, arg*);

#else /* K&R C */
extern bool_t xdr_arg ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_INFO_H_RPCGEN */
